# action.yml
name: "Semantic release"
description: 'This tool performs semantic release or returns value of next release version'
inputs:
  dry-run:  # if only version should be returned
    description: 'dry run'
    required: false
outputs:
  new_release_version:
    description: 'Version of the new release'
    value: ${{ steps.semantic.outputs.version }}
runs:
  using: 'composite'
  steps:
    - id: semantic
      run: npm install -D @semantic-release/changelog @semantic-release/git @semantic-release/exec;export NEXT_VERSION=$(npx semantic-release --dry-run | grep 'The next release version is' | sed -E 's/.* ([[:digit:].]+)$/\1/');echo version="$NEXT_VERSION" >> $GITHUB_OUTPUT
      shell: bash
    - id: semantic-publish
      run: npm install -D @semantic-release/changelog @semantic-release/git @semantic-release/exec;npx semantic-release
      shell: bash
