# action.yml
name: "Semantic release"
description: 'This tool performs semantic release or returns value of next release version'
inputs:
  dry-run:  # if only version should be returned
    description: 'Who to greet'
    required: false
outputs:
  new_release_version:
    description: 'Version of the new release'
    value: ${{ steps.version.outputs.version }}
runs:
  using: 'composite'
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: semantic.sh
      shell: bash
      
