name: build-test-release
on:
  push:
    branches:
      - "main"
      - "develop"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - "**"

jobs:
  release:
    runs-on: ubuntu-latest
    if: always()
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
    - name: Semantic Release
      id: semantic
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        npm -g install @semantic-release/git semantic-release && semantic-release --d
    - name: Docker meta
      id: docker_action_meta
      uses: docker/metadata-action@v4.1.1
      with:
        images: ghcr.io/${{ github.repository }}/container
        tags: |
          type=sha,format=long
          type=sha
          type=semver,pattern={{version}},value=${{ steps.version.outputs.new_release_version }}
          type=semver,pattern={{major}},value=${{ steps.version.outputs.new_release_version }}
          type=semver,pattern={{major}}.{{minor}},value=${{ steps.version.outputs.new_release_version }}
          type=ref,event=branch
          type=ref,event=pr

