on:
  push:
    branches:
      - main
      - beta

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: prep plugins
        run: npm install -D @semantic-release/changelog @semantic-release/git @semantic-release/exec
      - name: run semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
        id: ver
    outputs:
      output1: ${{ steps.ver.outputs.nextVer }}

  print:
    needs: release
    runs-on: ubuntu-20.04
    steps:
      - name: print version
        run: echo ${{ needs.release.outputs.output1}}
