name: build-test-release
on:
  push:
    branches:
      - "main"
      - "develop"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - "**"

jobs:
  release:
    runs-on: ubuntu-latest
    if: always()
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
    - name: prep plugins
      run: npm install -D @semantic-release/changelog @semantic-release/git @semantic-release/exec
    - name: Semantic Release
      id: ver
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        npx semantic-release
    outputs: 
      new_release_version: ${{ steps.ver.outputs.nextVer }}
      
  docker_meta:
    runs-on: ubuntu-latest
    needs: release
    steps:
    - name: docker meta
      id: docker_action_meta
      uses: docker/metadata-action@v4.1.1
      with:
        images: ghcr.io/${{ github.repository }}/container
        tags: |
          type=sha,format=long
          type=sha
          type=semver,pattern={{version}},value=${{ needs.release.outputs.new_release_version }}
          type=semver,pattern={{major}},value=${{ needs.release.outputs.new_release_version }}
          type=semver,pattern={{major}}.{{minor}},value=${{ needs.release.outputs.new_release_version }}
          type=ref,event=branch
          type=ref,event=pr

