on:
  push:
    branches:
      - main
      - beta

jobs:
   meta:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: false
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Semantic Release common
        id: semantic
        run: |
          npm install -D @semantic-release/changelog @semantic-release/git @semantic-release/exec
          export NEXT_VERSION=$(npx semantic-release --dry-run | grep 'The next release version is' | sed -E 's/.* ([[:digit:].]+)$/\1/')
          echo version="$NEXT_VERSION" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Semantic Release cycjimmy
        id: version
        uses: cycjimmy/semantic-release-action@v3.0.0
        with:
          semantic_version: 17
          extra_plugins: |
            @semantic-release/exec
            @semantic-release/git
            semantic-release-helm
            @google/semantic-release-replace-plugin
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: print versions
        run: |
          echo "cycjimmy: " ${{ steps.version.outputs.new_release_version }}
          echo "semantic: " ${{ steps.semantic.outputs.version }}

      - name: Docker meta
        id: docker_action_meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: ghcr.io/${{ github.repository }}/container
          tags: |
            type=sha,format=long
            type=sha
            type=semver,pattern={{version}},value=${{ steps.semantic.outputs.version }}
            type=semver,pattern={{major}},value=${{ steps.semantic.outputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.semantic.outputs.version }}
            type=ref,event=branch
            type=ref,event=pr
      - name: matrix
        id: matrix
        uses: splunk/addonfactory-test-matrix-action@v1.8
