name: build-test-release
on:
  push:
    branches:
      - "main"
      - "develop"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - "**"

jobs:
  call-workflow:
    runs-on: ubuntu-latest
    if: always()
    steps:
    - name: Semantic Release
      id: semantic
      uses: cycjimmy/semantic-release-action@v3.2.0
      with:
        semantic_version: 17
        extra_plugins: |
          @semantic-release/exec
          @semantic-release/git
          @semantic-release/commit-analyzer
          @semantic-release/release-notes-generator
          @semantic-release/github
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN_ADMIN }}
